### ISSUE TITLE
Booting from NVMe SSDs

### ISSUE THREAD

**Issue by 0pcom** [marotinhodimais/Maroto-iso#4]
I have not been able to get my new M3 drive to be bootable with portergos.
There is a chance it could be a hardware related issue, your thoughts?

**Comment by Portergos** [comment]
Hi!
I don't have SSD's, so i don't know if it works. AFAIK if Arch linux can boot in your system so can Portergos. Be sure you're using the latest version from https://github.com/Portergos/portergos-iso/releases

**Comment by 0pcom** [comment]
It works with SATA SSDs but I can't figure out booting on the newer 
NVMe SSDs which take an adaptor to PCIe

I can't figure it out with any OS so far, oh well. Thanks!

**Comment by Portergos** [comment]
Hi! Well, i really have no idea about SSDs, i have never got close to one. A possible study you can do is to check for similar problems with arch-based and even manjaro (and based) distros to your piece of hardware.

**Comment by 0pcom** [comment]
I got it to work on that NVMe SSD using a SATA to MicroSD adaptor and a small capacity microSD card; placing /boot on the microSD and installing the base system to the NVMe SSD.
